import { Clip } from '@/types/types';

// emergency fallback only
export const FALLBACK_CLIPS: Clip[] = [
  // movies
  {
    id: 'f1',
    tmdbId: 76341,
    title: 'Mad Max: Fury Road',
    description: 'Sandstorm Chase Scene',
    youtubeId: 'hEJnMQG9ev8',
    thumbnailUrl: 'https://img.youtube.com/vi/hEJnMQG9ev8/maxresdefault.jpg',
    category: 'action',
    mediaType: 'movie',
    year: 2015,
    popularity: 100,
    tags: ['clip', 'hd', 'iconic'],
    duration: 150,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f2',
    tmdbId: 155,
    title: 'The Dark Knight',
    description: 'Interrogation Scene',
    youtubeId: 'EXeTwQWrcwY',
    thumbnailUrl: 'https://img.youtube.com/vi/EXeTwQWrcwY/maxresdefault.jpg',
    category: 'action',
    mediaType: 'movie',
    year: 2008,
    popularity: 120,
    tags: ['clip', 'hd', 'iconic'],
    duration: 160,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'PG-13'
  },
  {
    id: 'f3',
    tmdbId: 27205,
    title: 'Inception',
    description: 'Hallway Fight Scene',
    youtubeId: 'YoHD9XEInc0',
    thumbnailUrl: 'https://img.youtube.com/vi/YoHD9XEInc0/maxresdefault.jpg',
    category: 'scifi',
    mediaType: 'movie',
    year: 2010,
    popularity: 110,
    tags: ['clip', 'hd', 'iconic'],
    duration: 140,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'PG-13'
  },
  {
    id: 'f4',
    tmdbId: 8363,
    title: 'Superbad',
    description: 'Best Scenes',
    youtubeId: 'z-nZ_S0Pib4',
    thumbnailUrl: 'https://img.youtube.com/vi/z-nZ_S0Pib4/maxresdefault.jpg',
    category: 'comedy',
    mediaType: 'movie',
    year: 2007,
    popularity: 80,
    tags: ['clip', 'hd'],
    duration: 300,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f5',
    tmdbId: 419430,
    title: 'Get Out',
    description: 'Sunken Place Scene',
    youtubeId: 'DzfpyUB60YY',
    thumbnailUrl: 'https://img.youtube.com/vi/DzfpyUB60YY/maxresdefault.jpg',
    category: 'horror',
    mediaType: 'movie',
    year: 2017,
    popularity: 95,
    tags: ['clip', 'hd', 'iconic'],
    duration: 155,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f6',
    tmdbId: 496243,
    title: 'Parasite',
    description: 'Ram-don Sequence',
    youtubeId: '5xH0HfJHsaY',
    thumbnailUrl: 'https://img.youtube.com/vi/5xH0HfJHsaY/maxresdefault.jpg',
    category: 'thriller',
    mediaType: 'movie',
    year: 2019,
    popularity: 105,
    tags: ['clip', 'hd', 'iconic'],
    duration: 140,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f7',
    tmdbId: 324857,
    title: 'Spider-Man: Into the Spider-Verse',
    description: 'Leap of Faith Scene',
    youtubeId: 'tg52up16eq0',
    thumbnailUrl: 'https://img.youtube.com/vi/tg52up16eq0/maxresdefault.jpg',
    category: 'animation',
    mediaType: 'movie',
    year: 2018,
    popularity: 115,
    tags: ['clip', 'hd', 'iconic'],
    duration: 165,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'PG'
  },
  {
    id: 'f8',
    tmdbId: 244786,
    title: 'Whiplash',
    description: 'Not My Tempo Scene',
    youtubeId: 'xDAsABdkWSc',
    thumbnailUrl: 'https://img.youtube.com/vi/xDAsABdkWSc/maxresdefault.jpg',
    category: 'drama',
    mediaType: 'movie',
    year: 2014,
    popularity: 90,
    tags: ['clip', 'hd'],
    duration: 210,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f9',
    tmdbId: 603,
    title: 'The Matrix',
    description: 'Dodge This',
    youtubeId: 'zYwdzYC3uUc',
    thumbnailUrl: 'https://img.youtube.com/vi/zYwdzYC3uUc/maxresdefault.jpg',
    category: 'scifi',
    mediaType: 'movie',
    year: 1999,
    popularity: 100,
    tags: ['clip', 'hd'],
    duration: 120,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f10',
    tmdbId: 12133,
    title: 'Step Brothers',
    description: 'Did We Just Become Best Friends?',
    youtubeId: 'QzBmQMyYDBk',
    thumbnailUrl: 'https://img.youtube.com/vi/QzBmQMyYDBk/maxresdefault.jpg',
    category: 'comedy',
    mediaType: 'movie',
    year: 2008,
    popularity: 85,
    tags: ['clip', 'hd'],
    duration: 60,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f11',
    tmdbId: 493922,
    title: 'Hereditary',
    description: 'Dinner Table Scene',
    youtubeId: 'V6wWKNij_1M',
    thumbnailUrl: 'https://img.youtube.com/vi/V6wWKNij_1M/maxresdefault.jpg',
    category: 'horror',
    mediaType: 'movie',
    year: 2018,
    popularity: 88,
    tags: ['clip', 'hd'],
    duration: 135,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  {
    id: 'f12',
    tmdbId: 807,
    title: 'Se7en',
    description: 'What\'s in the box?',
    youtubeId: '1giVzxyoclE',
    thumbnailUrl: 'https://img.youtube.com/vi/1giVzxyoclE/maxresdefault.jpg',
    category: 'thriller',
    mediaType: 'movie',
    year: 1995,
    popularity: 92,
    tags: ['clip', 'hd'],
    duration: 180,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'R'
  },
  
  // series (at least 8)
  {
    id: 's1',
    tmdbId: 1396,
    title: 'Breaking Bad',
    description: 'I Am The Danger',
    youtubeId: '31Vcj-w7P2Y',
    thumbnailUrl: 'https://img.youtube.com/vi/31Vcj-w7P2Y/maxresdefault.jpg',
    category: 'drama',
    mediaType: 'tv',
    year: 2011,
    popularity: 125,
    tags: ['clip', 'hd', 'iconic'],
    duration: 120,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-MA'
  },
  {
    id: 's2',
    tmdbId: 66732,
    title: 'Stranger Things',
    description: 'Running Up That Hill Scene',
    youtubeId: 'yQEondeGvKo',
    thumbnailUrl: 'https://img.youtube.com/vi/yQEondeGvKo/maxresdefault.jpg',
    category: 'scifi',
    mediaType: 'tv',
    year: 2022,
    popularity: 130,
    tags: ['clip', 'hd', 'iconic'],
    duration: 190,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-14'
  },
  {
    id: 's3',
    tmdbId: 1399,
    title: 'Game of Thrones',
    description: 'Battle of the Bastards',
    youtubeId: 'rlR4PJn8b8I',
    thumbnailUrl: 'https://img.youtube.com/vi/rlR4PJn8b8I/maxresdefault.jpg',
    category: 'action',
    mediaType: 'tv',
    year: 2016,
    popularity: 140,
    tags: ['clip', 'hd'],
    duration: 300,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-MA'
  },
  {
    id: 's4',
    tmdbId: 2316,
    title: 'The Office',
    description: 'Parkour!',
    youtubeId: '0Kvw2BPKjz0',
    thumbnailUrl: 'https://img.youtube.com/vi/0Kvw2BPKjz0/maxresdefault.jpg',
    category: 'comedy',
    mediaType: 'tv',
    year: 2009,
    popularity: 110,
    tags: ['clip', 'hd'],
    duration: 90,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-14'
  },
  {
    id: 's5',
    tmdbId: 67744,
    title: 'Mindhunter',
    description: 'Ed Kemper Interview',
    youtubeId: 'EDA_SmGZTxc',
    thumbnailUrl: 'https://img.youtube.com/vi/EDA_SmGZTxc/maxresdefault.jpg',
    category: 'thriller',
    mediaType: 'tv',
    year: 2017,
    popularity: 90,
    tags: ['clip', 'hd'],
    duration: 120,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-MA'
  },
  {
    id: 's6',
    tmdbId: 105248,
    title: 'Cyberpunk: Edgerunners',
    description: 'Sandevistan Scene',
    youtubeId: 'JtqIal1XmG8',
    thumbnailUrl: 'https://img.youtube.com/vi/JtqIal1XmG8/maxresdefault.jpg',
    category: 'animation',
    mediaType: 'tv',
    year: 2022,
    popularity: 105,
    tags: ['clip', 'hd'],
    duration: 160,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-MA'
  },
  {
    id: 's7',
    tmdbId: 73754,
    title: 'The Haunting of Hill House',
    description: 'Bent-Neck Lady Reveal',
    youtubeId: 'G9OzG53VwIk',
    thumbnailUrl: 'https://img.youtube.com/vi/G9OzG53VwIk/maxresdefault.jpg',
    category: 'horror',
    mediaType: 'tv',
    year: 2018,
    popularity: 85,
    tags: ['clip', 'hd'],
    duration: 145,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-MA'
  },
  {
    id: 's8',
    tmdbId: 76331,
    title: 'Succession',
    description: 'Boar on the Floor',
    youtubeId: 't3WeQow1_bE',
    thumbnailUrl: 'https://img.youtube.com/vi/t3WeQow1_bE/maxresdefault.jpg',
    category: 'drama',
    mediaType: 'tv',
    year: 2023,
    popularity: 115,
    tags: ['clip', 'hd', 'iconic'],
    duration: 130,
    posterPath: '/images/poster-placeholder.jpg',
    certification: 'TV-MA'
  }
];
